// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/yashraj-homepage/GrandClassic.tsx": () => import("../components/mockups/yashraj-homepage/GrandClassic.tsx"),
  "./components/mockups/yashraj-homepage/LuxuryDark.tsx": () => import("../components/mockups/yashraj-homepage/LuxuryDark.tsx"),
  "./components/mockups/yashraj-homepage/RoyalMinimal.tsx": () => import("../components/mockups/yashraj-homepage/RoyalMinimal.tsx")
};
